import { HomeSection } from "./components/HomeSection";
import Navbar from "./components/Navbar";

export const Portfolio = () => {
  return (
    <>
      <div className="static h-screen bg-content-image bg-cover">
        {/* Navbar */}
        <Navbar />

        {/* Home Section */}
        <HomeSection />
      </div>
      <h1 className="text-white">HOLAAAAAAAA</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
      <h1 className="text-main">HOLAAAAAAAA MI AMOOOOOOR TE PINCHIS AMOOOOOOOOOOOOOO CON MUCHAS OOOOOOOOOOOOOOOOOOOOOOOO</h1>
    </>
  );
};
